### ISSUE TITLE
Pros / Cons of each platform

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/paper-pearc_2017#2]
Some quick thoughts on each platform, feel free to add new comments / ideas below and I'll incorporate them.

[X/D] = addressed by XSEDE / Docker

Traditional bootcamp setup
---
* PRO: self sufficiency
* PRO: students are in a familiar computing environment
* CON: limited computing power on a laptop [X]
* CON: diversity across students in their setups (e.g., different OS, computational power, etc) [X/D]
* CON: Day-of startup costs installing and debugging  [X/D]
* CON: Materials can become stale and are harder to re-use / discover in the future  [X/D]
* CON: conflicts with other installs on the computer  [X/D]
* CON: no single point of control over student environments (e.g., if instructors want to change something) [X]
* CON: instructors often don't share computing environments [D]
* CON: instructor environments aren't the same as student environments [D]

XSEDE
---
* PRO: easier to start than amazon clusters
* CON: fewer online materials / self-guided learning
* CON: non-traditional computing environment for students
* CON: XSEDE itself isn't super well-known and needs to be learned
* CON: requires an allocation (credits / $$$) to get started
* PRO: fast allocation turnaround after submitting an application
* PRO: easily interfaces with docker

Docker
---
* CON: steep learning curve to be proficient
* PRO: however, relatively easy to get things done without being proficient
* PRO: standardizes computing environments across students and instructors
* PRO: piggy backing on other docker images for scientific computing
* PRO: can develop domain-specific images for particular applications
* PRO: widely used and useful outside of academia
* PRO: makes it possible to easily move to different computing infrastructures etc.

**Comment by arokem** [comment]
One more PRO for traditional bootcamp is that participants have the opportunity to install the software on the platform on which they are already doing their work (usually), and leave the workshop with the ability to keep going. XSEDE approaches that, but there are some additional bureaucratic hurdles to leap, so you can't just go back to your lab and keep working. 

Maybe that's what you meant by "self-sufficiency"?

**Comment by aculich** [comment]
@arokem the XSEDE+Docker approach provides some middle ground that just XSEDE by itself would not: with Docker people can take the software with them on their laptop back to their lab. 

When using a complex software stack (lots of software dependencies, with specific version requirements), Docker allows someone to go from zero-to-working much faster AND more reliably than installing it themselves by hand and the new software dependencies won't conflict/interfere with any work on projects they're already doing on their laptop.

Then, at their leisure, if the user wants to NOT use Docker for day-to-day use they can install the software directly on their laptop.

And because our approach with XSEDE makes use of Docker, it means that we don't have to change the software install process to use the Jetstream cloud... or for that matter, we could deploy it in the same way on AWS, but whichever cloud platform you pick, there are always bureaucratic/infrastructure setup steps and a learning curve.

**Comment by arokem** [comment]
There's the implicit assumption that researchers would choose to use Docker. But we didn't teach them anything about Docker in the workshop, and I doubt that many have adopted it as part of their workflow. To be honest, I don't even know what docker image I would have to pull to get the software we had in the workshop on my laptop...

**Comment by aculich** [comment]
Iterating on this approach for future workshops, I would want to provide instructions as part of the workshop materials.

Providing a server for all the students work means you can include all students (for those who don't have enough computing power on laptop) and skip the first-hour installfest (and it associated problems), but enabling students to walk out the door with the software is also beneficial.

In the future we might want to consider providing Docker instructions and/or laptop install instructions ahead of time, with the server option also being available.

For me there is also the additional issue of how to bridge the gap between the laptop and the advanced research computing resources that are available, but go underutilized.

**Comment by choldgraf** [comment]
Closing this now as we've got most of these incorporated into the manuscript
